apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: it-consulting-webapp-hpa
  namespace: it-consulting-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: it-consulting-webapp
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
